export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_BY_COUNTRY = 'FETCH_BY_COUNTRY';
export const FETCH_BY_LANGUAGE = 'FETCH_BY_LANGUAGE';


export const FETCH_MOVIE_DETAIL = 'FETCH_DATA';
export const FETCH_MOVIE_DETAIL_SUCCESS  = 'FETCH_MOVIE_DETAIL_SUCCCESS';
export const FETCH_MOVIE_DETAIL_FAILURE  = 'FETCH_MOVIE_DETAIL_FAILURE';

export const FETCH_SEARCHED_MOVIES = 'FETCH_SEARCHED_MOVIES';
export const FETCH_SEARCHED_MOVIES_SUCCESS  = 'FETCH_SEARCHED_MOVIES_SUCCESS';
export const FETCH_SEARCHED_MOVIES_FAILURE  = 'FETCH_SEARCHED_MOVIES_FAILURE';

export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SORT_BY_YEAR = 'SORT_BY_YEAR';

